import { BrainCircuit, Bot, Network } from 'lucide-react'

export const technologyData = [
  { type: 'ai' as const, title: 'Artificial intelligence', icon: BrainCircuit, copy: 'Machine intelligence designed to learn, adapt, and operate within complex environments.', tags: ['Machine learning', 'Computer vision'], detail: 'From perception to prediction, we explore intelligent models that help machines understand real-world information. Our work brings together computer vision, learning systems, and efficient inference at the edge.' },
  { type: 'robotics' as const, title: 'Robotics', icon: Bot, copy: 'Autonomous systems combining perception, control, and intelligent decision-making.', tags: ['Autonomy', 'Intelligent control'], detail: 'We connect sensing, planning, and precise control to help autonomous machines operate in changing environments. Our approach puts dependable interactions between people and machines at the center.' },
  { type: 'network' as const, title: 'Blockchain', icon: Network, copy: 'Distributed systems that make shared information verifiable, connected, and resilient.', tags: ['Distributed verification', 'Immutable records'], detail: 'We explore distributed architectures in which connected participants can verify a shared record. Cryptographic links and coordinated validation connect individual operations into a traceable system, without depending on a single point of trust.' },
]

export const projects = [
  { title: 'AI Vision Systems', category: 'ARTIFICIAL INTELLIGENCE', number: '01', tags: ['Computer vision', 'Edge AI'], copy: 'Helping machines see the world with greater clarity.', description: 'A research direction exploring how visual perception can help intelligent systems understand their surroundings. We bring image analysis, object recognition, and efficient on-device inference into one adaptable architecture.', focus: ['Visual perception and scene understanding', 'Efficient inference on edge devices', 'Modular integration with sensing systems'], type: 'vision' },
  { title: 'Autonomous Robotics', category: 'ROBOTICS & AUTOMATION', number: '02', tags: ['Autonomy', 'Sensor fusion'], copy: 'Intelligent machines. Purposeful movement.', description: 'Exploring autonomous systems that combine perception, planning, and responsive control. The goal is to help machines navigate changing spaces and work more naturally alongside people.', focus: ['Multi-sensor perception', 'Adaptive motion planning', 'Coordinated intelligent control'], type: 'robot' },
  { title: 'Smart Water Monitoring', category: 'CONNECTED ENVIRONMENTS', number: '03', tags: ['IoT', 'Environmental sensing'], copy: 'Better understanding of our most essential resource.', description: 'A connected sensing concept for understanding water conditions over time. Distributed measurements and clear data interpretation help make environmental change more visible.', focus: ['Distributed water quality sensing', 'Connected monitoring infrastructure', 'Interpretable environmental data'], type: 'water' },
  { title: 'Environmental Intelligence', category: 'APPLIED RESEARCH', number: '04', tags: ['Sensor networks', 'Data science'], copy: 'Turning environmental signals into meaningful insight.', description: 'Bringing together measurements from distributed sensors to build a more complete understanding of our surroundings. This research explores how connected observations can support informed decisions.', focus: ['Environmental signal processing', 'Multi-source data integration', 'Pattern detection over time'], type: 'environment' },
  { title: 'Edge AI Platform', category: 'INTELLIGENT INFRASTRUCTURE', number: '05', tags: ['Edge computing', 'Neural systems'], copy: 'Moving intelligence closer to where it matters.', description: 'A modular platform concept that brings machine learning capabilities to the source of data. Local processing enables responsive systems while reducing dependence on continuous cloud connectivity.', focus: ['Local neural inference', 'Modular hardware and software', 'Responsive connected applications'], type: 'edge' },
]


export type Project = (typeof projects)[number]
