import { chromium } from '@playwright/test'
import fs from 'node:fs/promises'

await fs.mkdir('.artifacts', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist'] })
const url = process.env.SCIFER_PREVIEW_URL || 'http://localhost:5173'
const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor: 1 })
const errors = []
page.on('pageerror', error => errors.push(error.message))
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
await page.goto(url, { waitUntil: 'networkidle' })
await page.locator('.experience-ready').waitFor({ timeout: 15000 })
await page.locator('.main-webgl canvas').waitFor({ timeout: 15000 })
await page.waitForTimeout(1400)
await page.screenshot({ path: '.artifacts/desktop-hero.png' })
console.log('INITIAL', JSON.stringify({ errors, canvas: await page.locator('canvas').count(), overflow: await page.evaluate(() => document.documentElement.scrollWidth > innerWidth) }))
await page.locator('#engineering').scrollIntoViewIfNeeded()
await page.waitForTimeout(1700)
await page.screenshot({ path: '.artifacts/desktop-engineering.png' })
await page.locator('#intelligence').scrollIntoViewIfNeeded()
await page.waitForTimeout(1400)
await page.screenshot({ path: '.artifacts/desktop-intelligence.png' })
await page.locator('#data').scrollIntoViewIfNeeded()
await page.waitForTimeout(1400)
await page.screenshot({ path: '.artifacts/desktop-data.png' })
await page.locator('#technology').scrollIntoViewIfNeeded()
await page.waitForTimeout(1800)
await page.screenshot({ path: '.artifacts/desktop-technology.png' })
await page.locator('#explorer').scrollIntoViewIfNeeded()
await page.waitForTimeout(1800)
await page.screenshot({ path: '.artifacts/desktop-explorer.png' })
await page.locator('#research').scrollIntoViewIfNeeded()
await page.waitForTimeout(1200)
await page.screenshot({ path: '.artifacts/desktop-research.png' })
await page.locator('#projects').scrollIntoViewIfNeeded()
await page.waitForTimeout(1000)
await page.screenshot({ path: '.artifacts/desktop-projects.png' })
await page.locator('#about').scrollIntoViewIfNeeded()
await page.waitForTimeout(1200)
await page.screenshot({ path: '.artifacts/desktop-connected.png' })
await page.locator('.final-section').scrollIntoViewIfNeeded()
await page.waitForTimeout(1200)
await page.screenshot({ path: '.artifacts/desktop-final.png' })
console.log('END', JSON.stringify({ errors }))
await page.close()
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
await mobile.goto(url, { waitUntil: 'networkidle' })
await mobile.locator('.experience-ready').waitFor({ timeout: 15000 })
await mobile.locator('.main-webgl canvas').waitFor({ timeout: 15000 })
await mobile.waitForTimeout(1400)
await mobile.screenshot({ path: '.artifacts/mobile-hero.png', fullPage: false })
console.log('MOBILE', JSON.stringify({ overflow: await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth) }))
for (const id of ['engineering', 'explorer', 'projects', 'about']) {
  await mobile.locator(`#${id}`).scrollIntoViewIfNeeded()
  await mobile.waitForTimeout(1400)
  await mobile.screenshot({ path: `.artifacts/mobile-${id}.png` })
}
await mobile.locator('.final-section').scrollIntoViewIfNeeded()
await mobile.waitForTimeout(1400)
await mobile.screenshot({ path: '.artifacts/mobile-final.png' })
for (const width of [320, 768, 1024]) {
  await mobile.setViewportSize({ width, height: width === 320 ? 740 : 1024 })
  await mobile.goto(url, { waitUntil: 'networkidle' })
  await mobile.locator('.experience-ready').waitFor({ timeout: 15000 })
  await mobile.waitForTimeout(900)
  console.log('RESPONSIVE', JSON.stringify({ width, overflow: await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth) }))
  await mobile.screenshot({ path: `.artifacts/responsive-${width}.png` })
}
await browser.close()
